# Generated by Django 5.1.4 on 2024-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teammate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
